
title: "Shahin Hossain"
description: "Researcher • Educator • AI & Education Thought Leader"
url: "https://shahinhossain.com"
baseurl: ""

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Analytics placeholder
analytics:
  google:
    id: "G-5KKHS386WV"

#logo
logo: /assets/images/logo.png

# Author info for footer or other uses
author:
  name: "Shahin Hossain"
  linkedin: "https://www.linkedin.com/in/shahin-hossain-82a02599/"

# Markdown & Syntax highlighting
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Exclude folders not needed
repo: ""
exclude:
  - node_modules
  - vendor
  - README.md
  - LICENSE
