title: "Professor Shahin Hossain"
email: "contact@shahinhossain.com"
description: "PhD Candidate | AI in Education | Researcher | Speaker"
baseurl: ""
url: "https://shahinhossain.com"
theme: minimal-mistakes-jekyll

author:
  name: "Shahin Hossain"
  avatar: "/assets/images/shahin-hossain.jpg"
