navigation:
  - title: "About"
    url: /about/
  - title: "CV"
    url: /cv/
  - title: "Publications"
    url: /publications/
  - title: "Contact"
    url: /contact/
footer:
  links: []
  content: ""
