navigation:
  - title: "About"
    url: /about/
  - title: "Publications"
    url: /publications/
  - title: "Speaking"
    url: /speaking/
  - title: "Consulting"
    url: /consulting/
  - title: "Media"
    url: /media/
  - title: "Webinars"
    url: /webinars/
  - title: "Contact"
    url: /contact/
  - title: "Book Now"
    url: "https://calendly.com/shahinh1"
    external: true
