# ───────────────────────────────────────────────────────────────────────────────
# Minimal Mistakes Theme + Site Metadata for Shahin Hossain
# ───────────────────────────────────────────────────────────────────────────────

# 1) Pull in Minimal Mistakes
remote_theme: mmistakes/minimal-mistakes

# 2) Plugins Minimal Mistakes uses
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-redirect-from
  - jekyll-seo-tag

# 3) Core Site Settings
title:       "Shahin Hossain"
description: "Researcher • Educator • AI & Education Thought Leader"
# Your GitHub Pages URL or custom domain:
url:         "https://shahinhossain.github.io"
baseurl:     ""               # leave blank if none
lang:        en
timezone:    America/New_York

# 4) Author / Profile Info
author:
  name:   "Shahin Hossain"
  avatar: "/assets/images/avatar.jpg"    # put your headshot here
  bio:    "Researcher, educator, and thought leader in AI for education."
  email:  "contact@shahinhossain.com"
  links:
    - label: "Email"
      icon:  "fas fa-envelope"
      url:   "mailto:contact@shahinhossain.com"
    - label: "GitHub"
      icon:  "fab fa-github"
      url:   "https://github.com/ShahinAbrar1"
    - label: "LinkedIn"
      icon:  "fab fa-linkedin"
      url:   "https://www.linkedin.com/in/shahinhossain"

# 5) SEO / Social Preview Defaults (minimal)
seo:
  title:       "Shahin Hossain"
  description: "Researcher • Educator • AI & Education Thought Leader"
  # og_image:   "/assets/images/social-preview.png"    # uncomment when you add one

# 6) Optional Analytics (fill in when ready)
analytics:
  google:
    id: ""          # UA-XXXXX-X or G-XXXXXXXXXX

# 7) Page defaults
defaults:
  - scope:
      path: ""      # all files
      type: posts
    values:
      layout: single
  - scope:
      path: ""      
      type: pages
    values:
      layout: single

# 8) Build Settings
markdown:      kramdown
highlighter:   rouge
permalink:     /:categories/:title/

# 9) Exclude from build
exclude:
  - node_modules
  - vendor
  - README.md
  - LICENSE

# ───────────────────────────────────────────────────────────────────────────────
# End of config
# ───────────────────────────────────────────────────────────────────────────────
