- name: Deploy to GitHub Pages
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_branch: main    # Add this line to specify your GitHub Pages branch
    publish_dir: ./_site
